// Server configuration

module.exports = {
  ENV: process.env.UPCHIEVE_SERVER_ENV,
  HOST: process.env.UPCHIEVE_SERVER_HOST,
  PORT: process.env.PORT || process.env.CLIENT_SERVER_PORT,
  CLIENT_HOST: process.env.UPCHIEVE_CLIENT_HOST,
  CLIENT_PORT: process.env.UPCHIEVE_CLIENT_PORT,
  SOCKET_PORT: process.env.UPCHIEVE_SERVER_SOCKETS_PORT,
  DB_HOST: process.env.UPCHIEVE_SERVER_DB_HOST,
  SESSION_SECRET: process.env.UPCHIEVE_SERVER_SESSION_SECRET,
  SALT_ROUNDS: 10,
  SENDGRID_API_KEY: process.env.UPCHIEVE_SENDGRID_API_KEY,
  SENDGRID_TEMPLATE_ID: process.env.UPCHIEVE_SENDGRID_TEMPLATE_ID,
  UPCHIEVE_NOREPLY_SENDER: process.env.UPCHIEVE_NOREPLY_SENDER,
  TWILIO_ACCOUNT_SID: process.env.UPCHIEVE_TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.UPCHIEVE_TWILIO_AUTH_TOKEN,
  TWILIO_SENDING_NUBER: process.env.UPCHIEVE_TWILIO_SENDING_NUMBER,
  CLEANSPEAK_API_KEY: process.env.UPCHIEVE_CLEANSPEAK_API_KEY,
  LETSENCRYPT_DIR: process.env.UPCHIEVE_LETSENCRYPT_DIR,
  VOLUNTEER_CODES: process.env.UPCHIEVE_VOLUNTEER_CODES,
  STUDENT_CODES: process.env.UPCHIEVE_STUDENT_CODES,
  isProd: () => this.ENV === 'production'
}
