version: "3"
services: 
    server:
        build: .
        ports:
            - "3000-3001:3000-3001"
        network_mode: host
        depends_on: 
            - db
    db:
        image: mongo:4.2.3-bionic
        environment:
            - MONGO_INITDB_DATABASE=upchieve
        volumes:
            - ./mongo-volume:/data/db
        network_mode: host